"
" dotphiles : https://github.com/dotphiles/dotphiles
"
" Setup vim and load required plugins before dotvim
"
" Authors:
"   Ben O'Hara <bohara@gmail.com>
"   Henning Bredel <h.bredel@gmx.de>
"

" Call dotvim
source ~/.vim/dotvim.vim

" Bundles {{{
if has("user_commands")
  set nocompatible
  filetype off
  set rtp+=~/.vim/bundle/vundle/
  call vundle#rc()
  "let g:vundles=['general', 'git', 'hg', 'programming', 'completion', 'ruby', 'python', 'misc']
  let g:vundles=['general', 'programming', 'git', 'html', 'completion']
  let g:neocomplcache_enable_at_startup = 1
  " Load 'vundles'
  source ~/.vim/vundles.vim
  " Add extra bundles here...
  " Bundle 'reponame'
endif
"}}}

" Customize to your needs...
" Misc {{{

set nocompatible	" use Vim settings, rather then Vi settings
set lazyredraw		" redraw only when we need to

syntax on               " Enable syntax highlighting
colorscheme desert     " Set nice looking colorscheme
"colorscheme badwolf     " Set nice looking colorscheme

"}}}
" UI Layout {{{
set showcmd         " show command in bottom bar
set number		    " show line numbers
set cursorline      " highlight current line

set wildmenu        " visual autocomplete for command menu
set showmatch       " highlight matching [{()}]


set laststatus=2    	" show status line

set statusline=%t   	" tail of the filename
set statusline+=%{&ff}	" file format
set statusline+=%h  	" help file flag
set statusline+=%m  	" modified flag
set statusline+=%r  	" read-only flag
set statusline+=%y  	" file type
set statusline+=%c, 	" cursor column
set statusline+=%l/%L	" cursor line/total lines
set statusline+=\ %P	" percent through file
"}}}
" Tabs and Spaces {{{
set tabstop=4       " number of visual spaces per TAB
set softtabstop=4   " number of spaces in tab when editing
set expandtab       " tabs are spaces

filetype indent on  " load filetype-specific indent fileset cursorline
"}}}
" Searching {{{
set incsearch           " search as characters are entered
set hlsearch            " highlight matches

" turn off search highlight
nnoremap <leader><space> :nohlsearch<CR>

"}}}
" Folding {{{
set foldenable          " enable folding
set foldlevelstart=10   " open most folds by default
set foldnestmax=10      " 10 nested fold max
set foldmethod=indent   " fold based on indent level

" space open/closes folds
nnoremap <space> za
"}}}
" Key Mappings {{{


" move vertical by visual line
nnoremap j gj
nnoremap k gk

" enable simple escape
inoremap jk <esc>
" }}}
" Backup {{{
set backup
set backupdir=~/.vim-tmp,~/.tmp,~/tmp,/tmp
set backupskip=/tmp/*
set directory=~/.vim-tmp,~/.tmp,~/tmp,/tmp
set writebackup
"}}}

set modelines=1		" local config from last line
" vim:foldmethod=marker:foldlevel=0
